name: Continuous Delivery
on:
  push:
    branches:
      - main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: projeto zipado
          path: |
            **.py
            README.md
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: projeto zipado
      - name: Display structure of downloaded files
        run: ls -R